// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzkqxvuelejpgryexzzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3F4dnVlbGVqcGdyeWV4enpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzQxNzIsImV4cCI6MjA2NjkxMDE3Mn0.us2D7PwAnho0fxrejfi6f4dWiJ-8rAm1t9mAcu502pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});