// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpphdmhqdabuifmynqvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcGhkbWhxZGFidWlmbXlucXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTAzODQsImV4cCI6MjA2Njk2NjM4NH0.cXDzUpceDhQR5zstk2H-RA3LrLxRV9kWEgaY6HLCH34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});